spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/vsplay
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        show_sql: true
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

jwt:
  key: ${VSPLAY_JWT_KEY}
  issuer : ${VSPLAY_ISSUER}
  access-token-expiration-minutes: 60

aws:
  s3:
    bucket-name: ${VSPLAY_S3_NAME}
  credentials:
    access-key : ${VSPLAY_S3_ACCESS_KEY}
    secret-key: ${VSPLAY_S3_SECRET}
  region: ${VSPLAY_S3_REGION}

