spring:
  application:
    name: app
  profiles:
    active: ${SPRING_PROFILE_ACTIVE}
  config:
    import: "optional:classpath:application-${spring.profiles.active}.yml"  # ✅ 프로파일을 자동으로 감지

logging:
  config: classpath:logback-spring.xml
