app:
  base-domain: ${VSPLAY_APP_BASE_URL}

spring:
  datasource:
    url: jdbc:mysql://${DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        format_sql: true
        use_sql_comments: true
        show_sql: true
        order_updates: true
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
jwt:
  key: ${VSPLAY_JWT_KEY}
  issuer : ${VSPLAY_ISSUER}
  access-token-expiration-minutes: 60

aws:
  s3:
    bucket-name: ${VSPLAY_S3_NAME}
  credentials:
    access-key : ${VSPLAY_S3_ACCESS_KEY}
    secret-key: ${VSPLAY_S3_SECRET}
  region: ${VSPLAY_S3_REGION}

