spring:
  mail:
    default-encoding: UTF-8
    username: ${PICKSY_SMTP_USER}
    password: ${PICKSY_SMTP_PASSWORD}
    host: email-smtp.ap-northeast-2.amazonaws.com
    port: 587
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
